//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoService
    {
        public int IdPhoto { get; set; }
        public int IdService { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
