//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.EF
{
    using System;
    using System.Collections.Generic;
    using LanguageSchool.ClassHelper;
    using System.Linq;
    
    public partial class ServiceHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceHistory()
        {
            this.ServiceHistoryAttachment = new HashSet<ServiceHistoryAttachment>();
        }
    
        public int IdServiceHistory { get; set; }
        public int IdClient { get; set; }
        public int IdService { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Comment { get; set; }
        public bool IsCanceled { get; set; }
        
        public string GetServiceName
        {
            get
            {
                return AppData.Context.Service.Find(IdService).ServiceName;
            }
        }
        public string GetTime
        {
            get
            {
                return StartTime.ToString();
            }
        }
        public int GetFilesCount
        {
            get
            {
                return AppData.Context.ServiceHistoryAttachment.Where(i => i.IdServiceHistory == IdServiceHistory).Count();
            }
        }

        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceHistoryAttachment> ServiceHistoryAttachment { get; set; }
    }
}
